#!/bin/bash
# Quick Reference - AI Electronics Chatbot

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║    🤖 AI ELECTRONICS CHATBOT - QUICK REFERENCE 🤖        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📂 PROJECT STRUCTURE"
echo "   ai-chatbot/"
echo "   ├── server.js              (Backend API)"
echo "   ├── database.js            (SQLite setup)"
echo "   ├── .env                   (Configuration)"
echo "   ├── package.json           (Backend deps)"
echo "   └── frontend/              (React app)"
echo "       ├── src/App.jsx        (Chat UI)"
echo "       └── package.json       (Frontend deps)"
echo ""
echo "🚀 GETTING STARTED"
echo "   1. Add OpenAI API key to .env"
echo "   2. Terminal 1: npm run dev              (Backend on :5000)"
echo "   3. Terminal 2: cd frontend && npm run dev (Frontend on :3000)"
echo "   4. Open: http://localhost:3000"
echo ""
echo "📡 API ENDPOINTS"
echo "   GET  /api/products                - All products"
echo "   GET  /api/products/search?q=term  - Search products"
echo "   POST /api/chat                    - Send message to AI"
echo "   POST /api/cart/add                - Add to cart"
echo "   GET  /api/cart/:userId            - View cart"
echo "   POST /api/orders                  - Create order"
echo "   GET  /api/orders/:userId          - View orders"
echo ""
echo "💬 EXAMPLE CHATS"
echo "   ✓ 'Show me wireless headphones'"
echo "   ✓ 'I need a mechanical keyboard for gaming'"
echo "   ✓ 'What's the best storage solution?'"
echo "   ✓ 'Add the keyboard to my cart'"
echo "   ✓ 'How much is the webcam?'"
echo ""
echo "🛠️  USEFUL COMMANDS"
echo "   npm run dev           - Start backend"
echo "   npm run start         - Alternative start"
echo "   cd frontend && npm run dev  - Start frontend"
echo "   curl localhost:5000/api/health - Test backend"
echo ""
echo "📊 DATABASE TABLES"
echo "   • users        - Customer accounts"
echo "   • products     - Electronics catalog (8 items)"
echo "   • cart         - Shopping carts"
echo "   • orders       - Customer orders"
echo "   • order_items  - Items in orders"
echo "   • conversations - Chat history"
echo ""
echo "📦 TECH STACK"
echo "   Frontend: React 18 + Vite + CSS"
echo "   Backend:  Node.js + Express"
echo "   Database: SQLite3"
echo "   AI:       OpenAI GPT-3.5-turbo"
echo ""
echo "🔐 SECURITY"
echo "   • .env is in .gitignore (never commit secrets!)"
echo "   • API keys should be environment variables"
echo "   • Database is local SQLite (demo only)"
echo ""
echo "❓ TROUBLESHOOTING"
echo "   CORS Error       → Check backend is on :5000"
echo "   API Key Error    → Verify OPENAI_API_KEY in .env"
echo "   Port in Use      → Kill process or change PORT in .env"
echo "   Module Not Found → Run: npm install && cd frontend && npm install"
echo ""
echo "📚 DOCUMENTATION"
echo "   • README.md  - Full documentation"
echo "   • SETUP.md   - Setup instructions"
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         Questions? Check README.md for details!           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
